name: Rollback Pipeline

on:
  workflow_dispatch:

jobs:
  rollback:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Rollback to previous version
      run: |
        # Rollback logic to deploy previous stable version
        # Example: Update ECS service to use previous image version
